# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartSipAppV0' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartSipAppV0

  target 'SmartSipAppV0-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartSipAppV0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SmartSipAppV0-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartSipAppV0-tvOS

  target 'SmartSipAppV0-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
